# Generated by Django 5.2.8 on 2025-11-19 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('upload.completed', 'Upload Completed')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
